(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var ipa=function(a){a.u||(a.u=new g.Xn,g.B(a,a.u));return a.u},J2=function(a){a.R("cardstatechange",g.uL(a)&&g.vL(a)?1:0)},jpa=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.Xj&&a.dataset){if(g.fc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.ed("pollChoiceIndex"))},kpa=function(a){return Math.pow(a,3)},lpa=function(a){return 3*a*a-2*a*a*a},K2=function(a,b){(0,g.y)(b,function(c){c={csn:a,
ve:g.Jr(c),eventType:4};var d={Wj:g.Ur(a),ai:a};"UNDEFINED_CSN"==a?g.gs("visualElementShown",c,d):g.Wq("visualElementShown",c,g.cr,d)})},L2=function(a,b){(0,g.y)(b,function(c){var d=void 0;
d=void 0===d?!1:d;c={csn:a,ve:g.Jr(c),eventType:d?16:8};d={Wj:g.Ur(a),ai:a,aE:d};"UNDEFINED_CSN"==a?g.gs("visualElementHidden",c,d):g.Wq("visualElementHidden",c,g.cr,d)})},O2=function(a){a=g.Ka(a);
delete M2[a];g.Vb(M2)&&N2&&N2.stop()},npa=function(){N2||(N2=new g.L(function(){mpa()},20));
var a=N2;a.isActive()||a.start()},mpa=function(){var a=(0,g.H)();
g.Ib(M2,function(b){opa(b,a)});
g.Vb(M2)||npa()},P2=function(a,b,c,d){g.Sn.call(this);
if(!g.Fa(a)||!g.Fa(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.w=a;this.M=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.H=0;this.F=null},opa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.H=1E3/(b-a.F);a.F=b;ppa(a,a.progress);1==a.progress?(a.o=0,O2(a),a.qd(),a.A()):1==a.o&&a.Ps()},ppa=function(a,b){g.Ha(a.G)&&(b=a.G(b));
a.coords=Array(a.w.length);for(var c=0;c<a.w.length;c++)a.coords[c]=(a.M[c]-a.w[c])*b+a.w[c]},qpa=function(a,b){g.je.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.H;this.state=b.o},Q2=function(a,b,c,d,e){P2.call(this,b,c,d,e);
this.element=a},R2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
Q2.call(this,a,b,c,d,e)},S2=function(a){g.A.call(this);
this.u=a||window;this.o=[]},rpa=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.Lq(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},T2=function(a){return a.baseUrl||null},spa=function(a,b,c){function d(tb){var Za=tb.hovercardButton;
if(!Za)return null;Za=Za.subscribeButtonRenderer;if(!Za)return null;var vc=f(Za.unsubscribedButtonText),af=f(Za.subscribedButtonText);if(Za.subscribed){var bf=f(Za.subscriberCountWithUnsubscribeText);var xh=f(Za.subscriberCountText)}else bf=f(Za.subscriberCountText),xh=f(Za.subscriberCountWithSubscribeText);var cf=null;return tb.signinEndpoint&&(cf=g.Qb(tb,"signinEndpoint","webNavigationEndpointData","url"),!cf)?null:vc&&(af||cf)?{subscribed:Za.subscribed,subscribeText:vc,subscribeCount:bf,unsubscribeText:af,
unsubscribeCount:xh,enabled:Za.enabled,signinUrl:cf,classic:tb.useClassicSubscribeButton}:null}
function e(tb){if(tb){var Za=[],vc=tb.videoId;vc&&Za.push("v="+vc);(vc=tb.playlistId)&&Za.push("list="+vc);(tb=tb.startTimeSeconds)&&Za.push("t="+tb);return"/watch?"+Za.join("&")}}
function f(tb){if(!tb)return null;var Za=tb.simpleText;return Za?Za:tb.runs?(0,g.Fc)(tb.runs,function(vc){return vc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,z=null,C=!1,D=null,G=null,F=null,E=null,M=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(C=g.Qb(l,"browseEndpoint","browseId"))z=C,m="/channel/"+z;n=!1;q="new";(C=!!b.isSubscribe)?D=d(b):G=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Qb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(E=f(b.productPrice)),b.additionalFeesText&&(M=f(b.additionalFeesText)),(n=g.Qb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Qb(b,"title","accessibility","accessibilityData","label");var X=b.endpoint?b.endpoint.clickTrackingParams:null,bb="";if(b.metadata){var uc=f(b.metadata);uc&&(bb=uc)}return{id:"element-"+c,type:k,title:f(b.title),metadata:bb,callToAction:f(b.callToAction),
Vv:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:z,subscribeButton:D,subscribersText:G,isSubscribe:C,targetUrl:m,AF:n,Nb:{itct:X},sO:q,Nj:a?a:null,EF:b.isPlaceholder,impressionUrls:(0,g.Fc)(b.impressionUrls||[],T2),qF:(0,g.Fc)(b.hovercardShowUrls||[],T2),clickUrls:(0,g.Fc)(l.loggingUrls||[],T2),visualElement:g.Ir(b.trackingParams),
productPrice:E,additionalFeesText:M}},U2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=(0,g.Fc)(a.impressionUrls||[],T2);a.trackingParams&&(c.visualElement=g.Ir(a.trackingParams));var d=(0,g.Fc)(a.elements||[],function(e,f){return spa(b,e,f)});
c.elements=(0,g.Vd)(d,function(e){return!!e});
return c},V2=function(a){g.uP.call(this,a);
this.A=this.u=null;this.o={};this.F={};this.C=this.w=null;this.H=[];a=a.P();this.M=g.yx(a)||g.Ax(a);this.J=!0;this.G=0;this.B=new g.qr(this);g.B(this,this.B);this.B.L(this.player,g.SD("creatorendscreen"),this.kG);this.B.L(this.player,"crx_creatorendscreen",this.lG);this.B.L(this.player,"resize",this.iy);this.B.L(window,"focus",this.pN);this.load();var b=g.Pd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ge(this,function(){g.Ud(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},tpa=function(a){return a.player.getVideoData().qc?"current":a.M?"new":"current"},W2=function(a){return"creator-endscreen-editor"===a.player.P().playerStyle},X2=function(a,b,c){c=void 0===c?!0:c;
g.LQ(a.player.app,"creatorendscreen",void 0);a.w&&(a.w.dispose(),a.w=null,a.C.dispose(),a.C=null);for(var d in a.o)a.o[d].dispose();a.o={};a.F={};0<a.H.length&&(a.H.forEach(function(l){l.dispose()}),a.H.length=0);
a.G=0;if((a.u=b)&&b.elements){c&&upa(a);c=[];d=new g.PD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.P().o||(a.w=new g.U({D:"div",I:"ytp-ce-shadow"}),g.FL(a.player,a.w.element,4),a.C=new g.ZL(a.w,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=vpa(a,e);a.o[e.id]=f;a.F[e.id]=e;g.FL(a.player,f.element,4);var k=new g.PD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);wpa(a,f,e)}g.BL(a.player,c);
a.iy()}},upa=function(a){var b=g.Rr(),c=g.Tr();
c&&b&&a.u.visualElement&&g.hs(c,b,[a.u.visualElement])},vpa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],N:{tabindex:"0","aria-label":b.Nj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],N:{tabindex:"0","aria-label":b.Nj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",N:Y2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",N:{href:Z2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],N:{dir:g.qn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],N:{tabindex:"0","aria-label":b.Nj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],N:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.qn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Y2(b)}]};c=new g.U(c);var d=g.Bd(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.P().o){var e=null;var f=b.Nb.itct}else e="endscreen",f=null;e=new g.aQ(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.H.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],N:{tabindex:"0","aria-label":b.Nj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",N:{dir:g.qn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],N:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Y2(b)},{D:"div",I:"ytp-ce-expanding-icon",N:xpa(b.iconUrl)}]};c=new g.U(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],N:{tabindex:"0","aria-label":b.Nj||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",N:{dir:g.qn(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],N:{href:Z2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",N:Y2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.U(c)}b.EF&&g.J(c.element,"ytp-ce-placeholder");return c},Y2=function(a){if(a.Vv)var b=a.Vv.thumbnails;
return xpa(b?b[b.length-1].url:null)},xpa=function(a){return a?{style:"background-image: url("+a+")"}:{}},wpa=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ha("mouseenter",(0,g.x)(a.Mr,a,b,c));b.ha("mouseleave",(0,g.x)(a.Us,a,b,c));a.player.P().o||b.ha("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.ha("click",(0,g.x)(a.Oz,a,c));b.ha("keypress",(0,g.x)(a.Oz,a,c));b.ha("focus",(0,g.x)(function(l,m){this.Mr(l,m)},a,b,c));
b.ha("blur",(0,g.x)(function(l,m){this.Us(l,m)},a,b,c));
b.ha("touchstart",(0,g.x)(a.Mr,a,b,c));var f=g.Dd("ytp-ce-expanding-overlay-hider",b.element);f&&b.L(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.nn(b.element,"ytp-ce-element-hover");g.nn(b.element,"ytp-ce-force-expand")});
b.ha("keydown",(0,g.x)(function(l,m){this.J=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.G+=n;0<this.G?(g.J(l.element,"ytp-ce-force-expand"),$2(this,m.id,!0)):(g.nn(l.element,"ytp-ce-force-expand"),g.nn(l.element,"ytp-ce-element-hover"),$2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.ha("blur",g.La(function(){"none"!=m.style.display&&a.J&&m.focus()})),l.L(m,"focus",d),l.L(m,"blur",e))},a,b);
c(g.Dd("ytp-sb-subscribe",b.element));c(g.Dd("ytp-sb-unsubscribe",b.element));b.ha("focus",d);b.ha("blur",e)},Z2=function(a,b){var c=a.player.P();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.$x(c)+b}else return"";return b},$2=function(a,b,c){a.w&&(c?a.C.show():a.C.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},a3=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||W2(a))c&&c();else{b=ypa(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Mp(b[a],d)}},b3=function(a,b,c){a3(a,b.clickUrls,c);
(a=g.Tr())&&b.AF&&g.js(a,b.visualElement)},ypa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(zpa(b[e],c));return d},zpa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Apa=function(a){return g.Fa(a)&&a.length?a[0]:a},c3=function(a){return"string"===typeof a?a:""},d3=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},Cpa=function(a){var b=Bpa;
if(null==a)return null;if(g.Ga(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},Dpa=function(a){this.externalId=a},Epa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},e3=function(a){if(!a)return null;
var b=g.zc(c3(a.value));b=g.xc(b);if(!b)return null;var c=d3(a.target,Fpa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Epa(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},f3=function(a){return a.value?a.value:null},Gpa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Bpa=function(a){if(!a)return null;
var b=d3(a.type,Hpa),c=d3(a.trigger,Ipa),d=Apa(a.url);d=e3(d?d:null);a=Apa(a.subscribeData);var e=a?a:null;e?(a=c3(e.external_user_id),e=c3(e.subscription_token),a=a&&e?new Dpa(a):null):a=null;return b?new Gpa(b,c,d,a):null},Jpa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Lpa=function(a){return(a=Kpa(a,function(b){return"openUrl"==b.type&&null!=b.url}))?a.url:null},Kpa=function(a,b){return g.Sa(a.o,b,void 0)},Mpa=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Npa=function(a,b){this.merchant=a;
this.price=b},Opa=function(a){this.o=a},Ppa=function(a,b,c){b&&(c?g3(a,(0,g.Fc)(b,g.La(function(d,e){return g.dn(e,d)},c))):g3(a,b))},g3=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.Mp(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Qpa=function(a,b,c,d,e,f,k){this.o=a;
this.w=b;this.ab=c;this.videoData=d;this.logger=e;this.ba=f;this.u=k},h3=function(a,b){this.o=a;
this.w=b},Tpa=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Rpa(b,k))},a);
var d={D:"ul",N:{role:"radiogroup"},K:c},e={};b.fi&&(e["aria-label"]=g.EM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[i3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.fi&&(f.push("iv-card-unavailable"),d.push({D:"div",X:["iv-card-sign-in"],K:[{D:"h2",W:"Want to vote?"},{D:"a",X:["iv-card-sign-in-button","iv-button"],N:{href:f3(b.fi)},K:[{D:"span",X:["iv-button-content"],W:"Sign in"}]}]}));f=new g.U({D:"div",
X:f,K:d});d=f.element;Spa(b,d);rpa(a.o.o,d,g.La(a.A,b),a);(0,g.y)(g.Cd("iv-card-poll-choice-input",d),function(k){this.o.o.ha(k,"focus",g.La(this.u,!0));this.o.o.ha(k,"blur",g.La(this.u,!1))},a);
b.fi&&(d=g.Dd("iv-card-sign-in-button",d),a.w(d,b.fi,b.id,b.Nb,b.Cc.click,5));return f},Upa=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.LO?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.DF&&b.vv?{D:"span",X:d,N:e,W:b.vv}:"";c={D:"div",X:["iv-card",c],K:[{D:"a",I:"iv-click-target",N:{href:f3(b.url)},K:[j3(b.ii,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},k3(a,b)]}]}]};c=new g.U(c);l3(a,g.Cd("iv-click-target",c.element),b,b.url);return c},m3=function(a){return a.customMessage?
i3("div","iv-card-message",a.customMessage):""},j3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",N:{style:c},K:d}},k3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(i3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Rpa=function(a,b){return{D:"li",
I:Mpa(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",N:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},i3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},i3=function(a,b,c){b?"string"===typeof b?b={"class":b}:g.Fa(b)&&(b={"class":b.join(" ")}):
b={};
b.dir=g.qn(c);return{D:a,N:b,W:c}},Vpa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.wm&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.wm+");");c.dir=g.qn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",X:b,N:c,K:d}},Spa=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Dd(Mpa(a,e.index),b);e=e.count/c;null==a.ze&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.ze==d);f.getElementsByTagName("input")[0].checked=a.ze==d;var k=Math.floor(100*e).toFixed(0),l=g.Dd("iv-card-poll-choice-percent",f);g.Zd(l,g.EM("$PERCENT%",{PERCENT:k}));f=g.Dd("iv-card-poll-result-bar",f);g.ph(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.ze);g.K(b,"iv-card-poll-expanded",
null!=a.ze&&1<a.choices.length)},l3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.w(e,d,c.id,c.Nb,c.Cc.click,5)},a)},Wpa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Xpa=function(a,b){return b?b:Wpa(a)?"current":"new"},n3=function(a,b){g.A.call(this);
this.o=a;this.context=b;this.gu=!1},Ypa=function(a,b,c,d,e){var f=f3(b);
if(f){var k=Xpa(f,b.target),l=(0,g.x)(function(){b.o&&this.context.ba.pauseVideo();var m=this.context.videoData.qc||!1,n=g.mp(f||"");m&&n&&(n.v||n.list)?g.sT(this.context.ba.app,n.v,c,n.list,!1,void 0):g.IM(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);g3(a.context.logger,d,l,e);Wpa(f)||(a=g.Tr(),d=c.itct,a&&d&&g.js(a,g.Ir(d)))}},Zpa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},o3=function(a,b,c){return{mx:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
DB:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Wo:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},r3=function(a,b,c){n3.call(this,b,c);
var d=this;this.w=a;this.ga=this.Aa=this.C=this.za=!1;this.ea=null;this.Z=new g.L(g.Ca,c.ab.Pa?4E3:3E3);g.B(this,this.Z);this.sa=new g.L(g.Ca);g.B(this,this.sa);this.H=new h3(c,(0,g.x)(this.xj,this),(0,g.x)(this.Cn,this));this.V=new g.U({D:"div",I:"iv-drawer",N:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",N:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],N:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.B(this,this.V);this.F=this.V.element;this.ka=new g.ZL(this.V,330);g.B(this,this.ka);this.ya=g.Dd("iv-drawer-header-text",this.F);this.B=g.Dd("iv-drawer-content",this.F);this.A=[];this.wa=this.T=this.G=this.da=this.u=null;this.U=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Aa&&p3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Aa=d.C)&&q3(d)});
this.O=this.M=this.aa=null;this.J=0},$pa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){p3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){q3(a)});
var c=b.data.headerText;g.Zd(a.ya,c);a.T&&a.T.setAttribute("title",c);a.aa=g.Ir(b.data.trackingParams);a.O=g.Ir(b.data.closeTrackingParams);a.M=g.Ir(b.data.iconTrackingParams)},aqa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.J;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"simple",teaserText:g.dA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Cc:o3(d,e,d.command),Td:d.trackingParams?g.Ir(d.trackingParams):null,Nd:e.trackingParams?
g.Ir(e.trackingParams):null,kd:f&&f.trackingParams?g.Ir(f.trackingParams):null,imageUrl:t3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.dA(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,wm:null,title:d.title?g.dA(d.title):"",customMessage:d.callToAction?g.dA(d.callToAction):"",url:d.command.urlEndpoint.url?e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.command.urlEndpoint.url}):null};u3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"collaborator",teaserText:g.dA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Cc:o3(d,e,d.endpoint),Td:d.trackingParams?g.Ir(d.trackingParams):null,Nd:e.trackingParams?g.Ir(e.trackingParams):null,kd:f&&f.trackingParams?
g.Ir(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.dA(d.customText):null,EA:t3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.dA(d.channelName):"",metaInfo:[d.subscriberCountText?g.dA(d.subscriberCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};u3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"playlist",teaserText:g.dA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Cc:o3(d,e,d.action),Td:d.trackingParams?g.Ir(d.trackingParams):null,Nd:e.trackingParams?g.Ir(e.trackingParams):null,kd:f&&f.trackingParams?g.Ir(f.trackingParams):
null,ii:t3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.dA(d.customMessage):null,playlistVideoCount:g.dA(d.playlistVideoCount),title:d.playlistTitle?g.dA(d.playlistTitle):"",metaInfo:[d.channelName?g.dA(d.channelName):"",d.videoCountText?g.dA(d.videoCountText):""],url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Zpa(d.action)})};u3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.J,type:"video",teaserText:g.dA(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Nb:s3(a,c,b,d),sponsored:!1,Cc:o3(d,e,d.action),Td:d.trackingParams?g.Ir(d.trackingParams):null,Nd:e.trackingParams?g.Ir(e.trackingParams):null,kd:f&&f.trackingParams?g.Ir(f.trackingParams):null,ii:t3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.dA(d.lengthString):null,customMessage:d.customMessage?g.dA(d.customMessage):null,title:d.videoTitle?g.dA(d.videoTitle):"",metaInfo:[d.channelName?g.dA(d.channelName):"",d.viewCountText?g.dA(d.viewCountText):""],isLiveNow:!!d.badge,url:e3({pause_on_navigation:!a.context.videoData.ua,target:"new",value:Zpa(d.action)})};u3(a,c)}a.J++},t3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},s3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},cqa=function(a,b){var c=bqa(a,b);
c&&(c==a.u&&(a.u=null),a.w.removeCueRange(c.card.id),g.Ud(c.Vp),g.$a(a.A,c),a.ym(),v3(a))},p3=function(a,b,c){if(!a.C){a.ka.show();
a.da=new g.L(function(){g.J(g.lL(a.context.ba),"ytp-iv-drawer-open")},0);
a.da.start();a.ea=g.Cq(a.B,"mousewheel",(0,g.x)(a.HG,a));a.C=!0;var d=g.Tr();d&&a.aa&&a.O&&K2(d,[a.aa,a.O]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.Sx||(f.Sx=!0,Ppa(a.context.logger,f.card.Cc.mx,e));d&&K2(d,[f.card.Td])});
J2(a.w);c&&(a.G=new g.L(function(){a.oa=a.T;a.wa.focus()},330),a.G.start())}},q3=function(a){a.C&&(a.ka.hide(),g.Dq(a.ea),a.ea=null,g.nn(g.lL(a.context.ba),"ytp-iv-drawer-open"),a.C=!1,J2(a.w),a.G&&a.G.stop(),a.G=new g.L(function(){a.oa&&(a.oa.focus(),a.oa=null)},330),a.G.start())},dqa=function(a){var b=g.Dd("iv-drawer-close-button",a.F);
a.context.o.ha(b,"click",a.HD,a);a.context.o.ha(a.B,"touchend",function(){a.Z.start()});
a.context.o.ha(a.B,"scroll",a.WD,a);a.context.u.subscribe("onHideControls",function(){a.ga=!0});
a.context.u.subscribe("onShowControls",function(){a.ga=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ga=g.ln(g.lL(a.w),"ytp-autohide")});
a.U.push(g.No("iv-button-shown",a.MF,a));a.U.push(g.No("iv-button-hidden",a.LF,a));a.U.push(g.No("iv-teaser-shown",a.PF,a));a.U.push(g.No("iv-teaser-hidden",a.OF,a));a.U.push(g.No("iv-teaser-clicked",a.NF,a))},u3=function(a,b){a.za||(g.mn(a.o,["html5-stop-propagation",
"iv-drawer-manager"]),g.FL(a.w,a.F,5),dqa(a),a.T=g.Dd("ytp-cards-button",g.lL(a.w)),a.wa=g.Dd("iv-drawer-close-button",a.F),a.za=!0);cqa(a,b.id);var c=eqa(a,b);if(c){var d={card:b,Vp:c.element,Sx:!1},e=fqa(a,d);g.gb(a.A,e,0,d);c.ca(a.B,e);a.ym();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.La(a.eO,d)):(c=1E3*a.context.ba.getCurrentTime(),5E3>c&&c>b.startMs&&a.iB(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.La(a.iB,d)),v3(a))}},eqa=function(a,b){switch(b.type){case "simple":var c=a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=Vpa(b);d={D:"div",X:["iv-card"],K:[{D:"a",I:"iv-click-target",N:{href:f3(b.url)},K:[j3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[i3("h2",void 0,b.title),e]}]}]};d=new g.U(d);l3(c,g.Cd("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],N:{href:f3(b.url),"data-ytid":b.channelId},K:[j3(b.EA),{D:"div",I:"iv-card-content",
K:[m3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},k3(c,b)]}]}]},d=new g.U(d),l3(c,g.Cd("iv-click-target",d.element),b,b.url),d;case "episode":return Upa(a.H,b,"iv-card-episode");case "movie":return Upa(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",N:{href:f3(b.url)},K:[j3(b.ii,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[m3(b),
i3("h2","iv-card-primary-link",b.title),k3(c,b)]}]}]},d=new g.U(d),l3(c,g.Cd("iv-click-target",d.element),b,b.url),d;case "poll":return Tpa(a.H,b);case "productListing":c=a.H;var f=!g.Wa(b.offers);d=["iv-card"];e="";var k=Vpa(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",X:d,N:{tabindex:"0"},K:[{D:"a",
X:["iv-card-image","iv-click-target"],N:{style:"background-image: url("+b.imageUrl+");",href:f3(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Sponsored",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",N:{href:f3(b.url)},K:[i3("h2",e,b.title),k]}]}]};d=new g.U(d);
e=g.Pd("span");g.Zd(e,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.sb(e,"adInfo");l3(c,g.Cd("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"LIVE NOW"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",N:{href:f3(b.url)},K:[j3(b.ii,b.videoDuration?{D:"span",I:"iv-card-video-duration",W:b.videoDuration}:""),{D:"div",I:"iv-card-content",
K:[m3(b),i3("h2","iv-card-primary-link",b.title),k3(c,b),d]}]}]},d=new g.U(d),l3(c,g.Cd("iv-click-target",d.element),b,b.url),d}return null},fqa=function(a,b){if(0==a.A.length)return 0;
var c=g.Ta(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},gqa=function(a){return a.u?"productListing"==a.u.card.type:(0,g.ni)(a.A,function(b){return"productListing"==b.card.type})},v3=function(a){g.K(g.lL(a.w),"ytp-cards-shopping-active",gqa(a))},hqa=function(a,b){if(a.V.Ea()){var c=new P2([0,
a.B.scrollTop],[0,b.Vp.offsetTop],600,lpa);a.context.w.ha(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.w.ha(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.CC(a.V,!0),a.B.scrollTop=b.Vp.offsetTop,g.CC(a.V,!1)},w3=function(a){return a.u&&a.u.card?a.u.card:a.A[0]&&a.A[0].card?a.A[0].card:null},bqa=function(a,b){return g.Sa(a.A,function(c){return c.card.id==b})},x3=function(a,b,c){n3.call(this,a,b);
this.annotation=c;this.isActive=!1},iqa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},y3=function(a,b,c){x3.call(this,a,b,c);
this.w=null;this.G=!1;this.A=null;this.B=!1;this.u=this.F=this.C=null},z3=function(a,b,c){x3.call(this,a,b,c);
this.M=this.C=this.J=!1;this.G=5E3;this.B=null;this.H=g.Od("DIV","iv-promo-contents");this.w=this.A=this.u=null;this.F=new g.L(function(){this.u.setAttribute("aria-hidden",!0);g.Kh(this.A,!1);g.Kh(this.w,!0)},700,this);
g.B(this,this.F)},jqa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.o.setAttribute("aria-hidden",!0);a.o.setAttribute("aria-label","Promotion");a.o.tabIndex=0;var e=Lpa(a.annotation),f=b.image_url;if(f){var k=g.Od("DIV",["iv-promo-img","iv-click-target"]);f=g.Od("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Od("SPAN","iv-promo-video-duration",b.video_duration),
k.appendChild(f)):b.playlist_length&&(f=g.Od("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.xj(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.Od("A","iv-promo-txt"),g.Uc(f,f3(e)),a.u=f):a.u=g.Od("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Od("P",null,g.Od("STRONG",null,b.text_line_1));var m=g.Od("P",null,g.Od("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");g.Q(a.context.ab.experiments,
"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Od("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Od("BUTTON",["iv-button","iv-promo-button"],g.Od("SPAN","iv-button-content",f));var q=g.Od("DIV","iv-promo-button-container");q.appendChild(f);e&&a.xj(a.o,e,a.annotation.id,b.session_data,void 0,c)}g.J(a.u,"iv-click-target");e&&a.xj(a.u,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.Od("P",null,g.Od("SPAN",null,b.text_line_1)),
m=g.Od("P",null,g.Od("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Od("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.u,"iv-click-target"),e&&a.xj(a.u,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.u.appendChild(l);m&&a.u.appendChild(m);a.H.appendChild(a.u);q&&a.H.appendChild(q);c=g.Od("DIV","iv-promo-actions");a.w=g.Od("BUTTON",["iv-promo-expand","ytp-button"]);a.w.title="Expand";a.context.o.ha(a.w,"click",g.La(a.Pq,5E3),a);c.appendChild(a.w);g.Kh(a.w,!1);
a.context.o.ha(a.o,"mouseover",a.UE,a);a.context.o.ha(a.o,"mouseout",a.TE,a);a.context.o.ha(a.o,"touchend",g.La(a.Pq,5E3),a);a.A=g.Od("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Close";a.context.o.ha(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.NE:a.ME,a);c.appendChild(a.A);g.mn(a.o,d);k&&(a.o.appendChild(k),n&&k.appendChild(n));a.o.appendChild(a.H);a.o.appendChild(c)},kqa=function(a){a.C||a.M||a.B||(g.J(a.o,"iv-promo-collapsed"),a.C=!0,a.F.start())},lqa=function(a){a.F.stop();
a.C&&(g.on(a.o,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.u&&a.u.removeAttribute("aria-hidden"),g.Kh(a.w,!1),g.Kh(a.A,!0))},mqa=function(a,b){a.B||(a.B=g.wf(function(){A3(this);
kqa(this)},b,a))},A3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},B3=function(a){g.uP.call(this,a);
this.M=!1;this.H=0;this.F={};this.V=new Opa(a);this.B=new g.qr(this);g.B(this,this.B);this.C=this.w=null;this.B.L(this.player,"onVideoAreaChange",(0,g.x)(this.R,this,"onVideoAreaChange"));this.B.L(this.player,"onHideControls",(0,g.x)(this.R,this,"onHideControls"));this.B.L(this.player,"onShowControls",(0,g.x)(this.R,this,"onShowControls"));this.B.L(this.player,"resize",(0,g.x)(this.R,this,"resize"));this.B.L(this.player,"presentingplayerstatechange",(0,g.x)(this.R,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.QL,this);this.subscribe("resize",this.xo,this);this.player.P().F.subscribe("vast_info_card_add",this.pA,this);this.T=new g.qr(this);g.B(this,this.T);this.O=g.Od("DIV","video-custom-annotations");this.u=new g.U({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.B(this,this.u);g.FL(this.player,this.u.element,4);this.u.hide();this.A=new g.U({D:"div",X:["ytp-iv-video-content"]});g.B(this,this.A);g.Rd(this.A.element,g.Od("DIV","video-annotations",
this.O));this.G=this.o=null;this.J=[];nqa(this)&&this.load();var b=g.Pd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.ge(this,function(){g.Ud(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},oqa=function(){var a=g.Od("DIV",["annotation",
"annotation-type-custom"]);g.Kh(a,!1);return a},pqa=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},nqa=function(a){var b=a.player.P();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.hC||b.F.get(a.videoId)||g.Q(b.experiments,"allow_skip_annotations_invideo")&&(g.LB(a)||g.MB(a))?!0:!1},qqa=function(a,b,c){a.M=!0;
a.C=g.Hp(b,c)},rqa=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ia(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(rqa(a,e))}return c},sqa=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},vqa=function(a){var b=a.player.getVideoData();
if(b.Sd){var c=a.player.P().F.get(b.videoId);if(c){var d={format:"XML",Qd:{},method:"POST",withCredentials:!0};d.qd=(0,g.x)(function(e,f,k){sqa(this,e,f)||(e=g.Bp(k)&&k.responseXML?k.responseXML:null)&&C3(this,e)},a,a.H,b.videoId);
g.bp()&&(d.qd=tqa(a,d.qd));d.yb={ic_only:"1"};uqa(d,c);a.M=!0;g.Hp(b.Sd,d)}}},uqa=function(a,b){a.method="POST";
a.yb=a.yb||{};b.Cm&&(a.yb.ic_coll=b.Cm);b.Dm&&(a.yb.ic_xml=b.Dm);b.Pl&&(a.yb.ic_track=b.Pl)},wqa=function(a){var b=new g.U({D:"div"});
g.Kh(b.element,!1);var c=new r3(a.player,b.element,D3(a));g.B(c,b);b.ca(a.u.element);c.Bl();return c},D3=function(a){if(!a.G){var b=new S2(a);
g.B(a,b);var c=new g.w1(a);g.B(a,c);a.G=new Qpa(b,c,a.player.P(),a.player.getVideoData(),a.V,a.player,a.dc)}return a.G},C3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Tr();if(e){var f=g.Rr();f&&g.hs(e,f,[g.Ir(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=rqa(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=d3(k.type,xqa),t=d3(k.style,yqa),u=c3(k.data),z=0!=u.length?JSON.parse(u):{},C=Cpa(k.action);f=n&&q?new Jpa(n,q,t,C,z):null}else f=null}catch(M){}if(f){a:{switch(f.type){case "branding":case "promotion":k=!0;break a}k=
!1}if(k){k=a;m=f;var D=oqa(),G=null;switch(m.type){case "branding":if(k.player.P().Ka)break;k.u.element.appendChild(D);G=new y3(D,D3(k),m);break;case "promotion":g.FL(k.player,D,4),G=new z3(D,D3(k),m)}G&&G.Bl();if(k=G)g.B(a,k),a.F[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=wqa(a),g.B(a,a.o));if("card"==f.type){if(c=a.o,G=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={mx:k.impression,click:k.click,close:k.close,DB:k.teaser_impression,Wo:k.teaser_click},m=f.data.tracking_params||
{},D=null,G){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,EA:f.data.image_url,title:f.data.title,
metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):
null,ii:f.data.image_url,vv:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,DF:!!f.data.is_paygated,LO:!!f.data.user_has_entitlement,url:e3({target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||
!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):null,ii:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,
startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):null,title:f.data.title,choices:f.data.choices,ze:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,fi:f.data.signin_url?e3({target:"current",value:f.data.signin_url}):null,WO:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};u3(c,f);break;case "productListing":f.data.signin_url&&(D=e3({target:"current",
value:f.data.signin_url}));G=[];for(var F=f.data.offers||[],E=0;E<F.length;E++)G.push(new Npa(g.ad(F[E].merchant),g.ad(F[E].price)));f={bT:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):null,imageUrl:f.data.image_url,
displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,wm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),fi:D,pT:f.data.signin_title?f.data.signin_title:null,oT:f.data.signin_message?f.data.signin_message:null,offers:G};u3(c,f);break;case "simple":f={id:f.id,timestamp:f.data.timestamp||
0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):null,kd:m.icon?g.Ir(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,wm:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,
customMessage:f.data.custom_message?f.data.custom_message:null,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};u3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Nb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Cc:k,Td:m.card?g.Ir(m.card):null,Nd:m.teaser?g.Ir(m.teaser):
null,kd:m.icon?g.Ir(m.icon):null,ii:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:e3({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},u3(c,f)}}else $pa(a.o,f);c=!0}}}c&&(J2(a.player),a.xo())},zqa=function(a,b){var c=!1;
a.o||(a.o=wqa(a),g.B(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())aqa(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.dA(b.headerText):"",g.Zd(c.ya,d),c.T&&c.T.setAttribute("title",d),c.aa=b.trackingParams?g.Ir(b.trackingParams):null,c.O=b.closeButton.infoCardIconRenderer.trackingParams?g.Ir(b.closeButton.infoCardIconRenderer.trackingParams):null,c.M=b.icon.infoCardIconRenderer.trackingParams?g.Ir(b.icon.infoCardIconRenderer.trackingParams):null,J2(a.player),a.xo())},
Aqa=function(a,b,c,d,e){if(!a.player.P().Ka){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Gpa("openUrl","click",new Epa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.dA(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.dA(b.subscriberCountText))):(b.subscriberCountText&&(e=g.dA(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.dA(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.dA(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.dA(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Jpa(c,"branding","branding",f,d);d=oqa();a.u.element.appendChild(d);f=new y3(d,D3(a),f);f.Bl();g.B(f,f);a.F[c]=f}},tqa=function(a,b){return(0,g.x)(function(){if(!this.la()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.La.apply(window,c);this.J.push(g.$o(b))}},a)},M2={},N2=null;g.Na(P2,g.Sn);g.h=P2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.w;else if(1==this.o)return!1;O2(this);this.startTime=a=(0,g.H)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.F=this.startTime;this.progress||this.B();this.pe("play");-1==this.o&&this.pe("resume");this.o=1;var b=g.Ka(this);b in M2||(M2[b]=this);npa();opa(this,a);return!0};
g.h.stop=function(a){O2(this);this.o=0;a&&(this.progress=1);ppa(this,this.progress);this.pe("stop");this.A()};
g.h.pause=function(){1==this.o&&(O2(this),this.o=-1,this.pe("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.pe("destroy");P2.Db.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ps=function(){this.pe("animate")};
g.h.pe=function(a){this.dispatchEvent(new qpa(a,this))};
g.Na(qpa,g.je);g.Na(Q2,P2);Q2.prototype.C=g.Ca;Q2.prototype.Ps=function(){this.C();Q2.Db.Ps.call(this)};
Q2.prototype.A=function(){this.C();Q2.Db.A.call(this)};
Q2.prototype.B=function(){this.C();Q2.Db.B.call(this)};
g.Na(R2,Q2);R2.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(S2,g.A);S2.prototype.ha=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Cq(a,b,c);this.o.push(a);return a};
S2.prototype.Ar=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.Mq(a,b,c);this.o.push(a);return a};
S2.prototype.Xa=function(a){g.Dq(a);g.$a(this.o,a)};
S2.prototype.Y=function(){g.Dq(this.o);this.o.length=0;g.A.prototype.Y.call(this)};g.r(V2,g.uP);g.h=V2.prototype;g.h.load=function(){g.uP.prototype.load.call(this);if(!W2(this)){var a=g.KB(this.player.getVideoData());if(a)a=U2(a,tpa(this)),X2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.A&&this.A.abort();a={method:"POST",qd:(0,g.x)(this.CK,this,a),Qd:{v:a},withCredentials:!0};this.M&&(a.Qd.ptype="embedded");var c=this.player.getVideoData().Qm;c&&(a.yb={ad_tracking:c});if(b=g.JB(b))if(b=g.zc(b),b=g.xc(b))this.A=g.Hp(b,a)}}};
g.h.unload=function(){X2(this,null);this.A&&(this.A.abort(),this.A=null);g.uP.prototype.unload.call(this)};
g.h.Hc=function(a,b){if(!W2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=U2(b,"new");X2(this,c);return!0}return null};
g.h.getOptions=function(){return W2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.CK=function(a,b){var c=this.A=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=U2(c,tpa(this)))}X2(this,c)};
g.h.iy=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Bqa.length;f++){var k=Math.abs(b.width-Bqa[f]);if(-1==e||d>=k)e=f,d=k}d=Cqa[e];this.w&&g.ph(this.w.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.F[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Ih(e.element,Math.round(k.width*a.width),f);g.yh(e.element,m,n);g.on(e.element,Dqa);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.on(e.element,Cqa);g.J(e.element,d);(e=g.Bd(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ph(e,"height",f+"px")}}}}};
g.h.kG=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())a3(this,this.u.impressionUrls),(a=g.Tr())&&this.u.visualElement&&g.is(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.F[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");g.J(g.lL(this.player),"ytp-ce-shown");a3(this,c.impressionUrls);(b=g.Tr())&&g.is(b,c.visualElement);this.player.P().Cb&&this.player.ma("endscreenelementshown",a)}};
g.h.lG=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.nn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);g.nn(g.lL(this.player),"ytp-ce-shown");this.player.P().Cb&&this.player.ma("endscreenelementhidden",a)}};
g.h.pN=function(a){var b=this;a.target===window&&(new g.L(function(){for(var c in b.o)g.on(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.Oz=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.ln(c,"ytp-ce-element");){g.ln(c,"subscribe-label")&&b3(this,a);if(g.ln(c,"ytp-ce-channel-subscribe"))return;c=g.Xd(c)}if(!c||g.ln(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Us(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.sO?(b3(this,a),this.hB(),this.player.pauseVideo(),c=g.zc(Z2(this,a.targetUrl)),c=g.xc(c),g.IM(c,void 0,a.Nb)):(c=this.player.getVideoData().qc,
c=(0,g.x)(this.mO,this,c,Z2(this,a.targetUrl),a.Nb),c=(0,g.x)(this.hB,this,c),b3(this,a,c))}}};
g.h.mO=function(a,b,c){var d=g.mp(b);a&&d&&(d.v||d.list)?g.sT(this.player.app,d.v,c,d.list,!1,void 0):g.HM(b,c)};
g.h.Mr=function(a,b){g.ln(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):this.player.P().o?(new g.L(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),a3(this,b.qF),$2(this,b.id,!0))};
g.h.Us=function(a,b){g.nn(a.element,"ytp-ce-element-hover");g.nn(a.element,"ytp-ce-force-expand");$2(this,b.id,!1)};
g.h.hB=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var Bqa=[346,426,470,506,570,640,853,1280,1920],Cqa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Dqa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Fpa={bQ:"current",wR:"new"};var Hpa={CLOSE:"close",zR:"openUrl",cD:"subscribe"},Ipa={VP:"click",CLOSE:"close",MQ:"hidden",eS:"rollOut",fS:"rollOver",iS:"shown"};var yqa={yP:"anchored",xC:"branding",CHANNEL:"channel",aQ:"cta",OQ:"highlightText",fR:"label",PLAYLIST:"playlist",RR:"popup",mS:"speech",cD:"subscribe",wS:"title",VIDEO:"video",KS:"website"},xqa={xC:"branding",MP:"card",hQ:"drawer",NQ:"highlight",mR:"marker",WR:"promotion",TEXT:"text",MS:"widget"};h3.prototype.u=function(a,b){var c=g.de(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
h3.prototype.A=function(a,b){var c=g.de(b.target,null,"iv-card-poll",void 0);if(c)if(a.fi)g.Dd("iv-card-sign-in-button",c).click();else{var d=parseInt(jpa(b.target),10);if(null==a.ze)a.choices[d].count++,a.ze=d;else if(a.ze!=d){var e=a.choices[a.ze];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.ze=d}else e=a.choices[a.ze],e.count=Math.max(e.count-1,0),a.ze=null;Spa(a,c);g.Lp(this.o.videoData.Sd,{Qd:{action_poll_vote:1},yb:{poll_id:a.id,index:d,session_token:a.WO}});g3(this.o.logger,a.Cc.click,
void 0,5);(c=g.Tr())&&a.Td&&g.js(c,a.Td)}};g.r(n3,g.A);g.h=n3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.PD(a,b,{id:c});g.B(this,a);a.namespace="annotations_module";d&&ipa(a).subscribe("onEnter",d,this);e&&ipa(a).subscribe("onExit",e,this);g.BL(this.context.ba,[a])};
g.h.Bl=function(){this.context.u.subscribe("resize",this.ym,this)};
g.h.xj=function(a,b,c,d,e,f){this.context.o.ha(a,"click",g.La(this.Cn,b,c,d,e||[],f||0),this);this.context.o.ha(a,"touchstart",g.La(function(){this.gu=!1}),this);
this.context.o.ha(a,"touchmove",g.La(function(){this.gu=!0}),this)};
g.h.Cn=function(a,b,c,d,e,f){if(this.gu)return!1;f&&(f.stopPropagation(),f.preventDefault());Ypa(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Ud(this.o)};
g.h.ym=function(){};g.r(r3,n3);g.h=r3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=g.lL(this.w))?(a=g.Jh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.ym=function(){var a=this.isAvailable();g.Kh(this.o,a);g.K(g.lL(this.context.ba),"ytp-iv-drawer-enabled",a);J2(this.w)};
g.h.destroy=function(){var a=g.tL(g.gL(this.w));a&&a.Lr(!1,void 0);try{g.lL(this.w).removeChild(this.F)}catch(b){}g.Oo(this.U);g.Dq(this.ea);this.da&&this.da.dispose();this.G&&this.G.dispose();n3.prototype.destroy.call(this)};
g.h.HG=function(a){this.Z.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.iB=function(a){if(!g.ln(g.lL(this.w),"ytp-cards-teaser-shown")){if(this.u!=a){var b=g.Tr(),c=this.u?this.u.card.kd:this.M;b&&c&&L2(b,[c]);this.u=a;v3(this)}if(b="none"!=this.o.style.display)2==this.context.ba.getPresentingPlayerType()?b=1==this.context.ba.getAdState():(b=this.context.ba.getPlayerState(),c=0==b&&0===this.context.ba.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.tL(g.gL(this.w)))&&c.Lr(!0,b));
this.sa.isActive()||((!this.C||!this.Z.isActive()&&this.ga)&&hqa(this,a),this.sa.start(910+a.card.teaserDurationMs))}};
g.h.eO=function(a){this.C||(this.u=a,v3(this),hqa(this,a),p3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.HD=function(){if(this.C){g3(this.context.logger,w3(this).Cc.close);var a=g.Tr();a&&this.O&&g.js(a,this.O);q3(this)}};
g.h.WD=function(){g.K(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.MF=function(){var a=g.Tr(),b=w3(this);b=b?b.kd:this.M;a&&b&&K2(a,[b])};
g.h.LF=function(){var a=g.Tr(),b=w3(this);b=b?b.kd:this.M;a&&b&&L2(a,[b])};
g.h.PF=function(){var a=w3(this);g3(this.context.logger,a.Cc.DB);var b=g.Tr();b&&a&&K2(b,[a.Nd,a.kd])};
g.h.OF=function(){var a=g.Tr(),b=w3(this);a&&b&&L2(a,[b.Nd])};
g.h.NF=function(a){var b=w3(this),c=g.Tr();this.u?a?(a=this.context.logger,g3(a,b.Cc.Wo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Nd&&g.js(c,b.Nd)):(a=this.context.logger,g3(a,b.Cc.Wo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.kd&&g.js(c,b.kd)):(a=this.context.logger,g3(a,b.Cc.Wo),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.M&&g.js(c,this.M))};g.r(x3,n3);x3.prototype.Bl=function(){n3.prototype.Bl.call(this);iqa(this)};
x3.prototype.show=function(){n3.prototype.show.call(this);var a=g.Tr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&K2(a,[g.Ir(b.itct)])};
x3.prototype.hide=function(){n3.prototype.hide.call(this);var a=g.Tr(),b=this.annotation.data;a&&b&&(b=b.session_data)&&L2(a,[g.Ir(b.itct)])};g.r(y3,x3);g.h=y3.prototype;g.h.nO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Jh(a);this.u||(g.Hh(a,e.width),g.Hh(b,e.width));g.ph(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ph(c,"right","1px");this.B=!0;g.Kh(a,!0);this.C=new g.L(function(){g.J(this.o,"iv-branding-active")},0,this);
this.C.start()}};
g.h.pF=function(a,b){g.nn(this.o,"iv-branding-active");this.F=new g.L((0,g.x)(function(){g.Kh(a,!1);this.u||g.Hh(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){x3.prototype.show.call(this);if(!this.G){g.J(this.o,"iv-branding");var a=this.annotation.data;this.w=g.Od("IMG",{"aria-label":"Channel watermark",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Kh(this.w,!1);var b=g.Od("DIV","branding-img-container",this.w);this.o.appendChild(b);(b=Lpa(this.annotation))&&this.xj(this.w,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.Od("DIV","iv-branding-context-name");
g.Zd(c,a.channel_name);var d=g.Od("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.u=new g.aQ(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.ba),this.u.ca(d);b=g.Od("DIV","iv-branding-context-subscribe-caret");c=g.Od("DIV","branding-context-container-inner",b,c,d);g.Kh(c,!1);d=g.Od("DIV","branding-context-container-outer",c);g.ph(d,"right",
a.image_width+"px");this.o.appendChild(d);this.A=new g.L(g.La(this.pF,c,d),500,this);g.B(this,this.A);this.context.o.ha(this.o,"mouseover",(0,g.x)(this.nO,this,c,d,b,a.image_height));this.context.o.ha(this.o,"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Kh(this.o,!0);this.isActive=!0;if(this.w){a=this.w;var e=void 0===e?0:e;b=g.Ch(a);c=g.Jh(a);b=(new g.mh(b.x,b.y,c.width,c.height)).width;g.yh(a,b);e=new R2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,kpa);g.B(this,e);this.context.w.ha(e,
"begin",g.La(g.Kh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(x3.prototype.hide.call(this),g.Kh(this.o,!1),this.isActive=!1)};
g.h.destroy=function(){this.u&&(this.u.dispose(),this.u=null);x3.prototype.destroy.call(this)};g.r(z3,x3);g.h=z3.prototype;g.h.show=function(){this.isActive||(x3.prototype.show.call(this),this.J||(jqa(this),this.J=!0),g.Kh(this.o,!0),g.wf(function(){g.nn(this.o,"iv-promo-inactive")},100,this),this.o.removeAttribute("aria-hidden"),this.isActive=!0,A3(this),lqa(this),mqa(this,this.G))};
g.h.hide=function(){this.isActive&&(g.J(this.o,"iv-promo-inactive"),this.isActive=!1,this.o.setAttribute("aria-hidden",!0))};
g.h.Cn=function(a,b,c,d,e,f){return this.C?!1:x3.prototype.Cn.call(this,a,b,c,d,e,f)};
g.h.Pq=function(a,b){b.stopPropagation();lqa(this);mqa(this,a);this.u.focus()};
g.h.UE=function(a){this.M=!0;this.Pq(500,a)};
g.h.TE=function(){this.M=!1;kqa(this)};
g.h.ME=function(a){a.stopPropagation();this.hide()};
g.h.NE=function(a){a.stopPropagation();A3(this);this.C=!0;g.J(this.o,"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();x3.prototype.destroy.call(this)};g.r(B3,g.uP);g.h=B3.prototype;g.h.Hc=function(a,b){if(!pqa(this.player.P().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.u1(b);c&&C3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(cqa(this.o,b),J2(this.player)),!0}return null};
g.h.getOptions=function(){return pqa(this.player.P().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.xo=function(){if(this.A){var a=g.kL(this.player).getVideoContentRect(!0);g.Ih(this.A.element,a.width,a.height);g.yh(this.A.element,a.left,a.top)}if(this.o){var b=g.wL(this.player);a=this.o;b=b.width;g.K(a.F,"iv-drawer-small",426>=b);g.K(a.F,"iv-drawer-big",1280<=b)}};
g.h.QL=function(a){this.kc(a.state);g.V(a.state,2)&&(this.Qk()&&this.gy()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Lr(!1))};
g.h.load=function(){g.uP.prototype.load.call(this);this.kc(g.nL(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.EK,this,b,this.H),d=(0,g.x)(function(){this.C=null},this);
g.bp()&&(c=tqa(this,c));c={format:"XML",qd:c,onError:d,Qd:{}};a.isPharma&&(c.Qd.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.P().F.get(b))&&uqa(c,b);b=b&&(b.Dm||b.Cm);if(!a.pm||b)a.Sd?qqa(this,a.Sd,c):(this.w=(0,g.x)(this.iG,this,c),this.player.addEventListener("videodatachange",this.w));g.FL(this.player,this.A.element,4);this.xo();(b=g.LB(a))&&zqa(this,b);(b=g.MB(a))&&b.featuredChannel&&Aqa(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.kc=function(a){a=!a.isCued()&&!g.V(a,1024);g.CC(this.u,a);g.CC(this.A,a)};
g.h.iG=function(a){var b=this.player.getVideoData();b.Sd&&(this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null),qqa(this,b.Sd,a))};
g.h.unload=function(){g.LQ(this.player.app,"annotations_module",void 0);g.Ib(this.F,function(a){a.destroy()});
this.G=null;this.o&&(this.o.destroy(),this.o=null,J2(this.player));this.M=!1;this.C&&(this.C.abort(),this.C=null);this.F={};this.u.hide();g.uP.prototype.unload.call(this);g.zC(this.A);this.w&&(this.player.removeEventListener("videodatachange",this.w),this.w=null)};
g.h.EK=function(a,b,c){this.C=null;!sqa(this,b,a)&&(a=g.Bp(c)&&c.responseXML?c.responseXML:null)&&(C3(this,a),g.J(g.lL(this.player),"iv-module-loaded"))};
g.h.pA=function(a){a==this.player.getVideoData().videoId&&(this.loaded?vqa(this):this.load())};
g.h.Qk=function(){return!!this.o&&this.o.isAvailable()};
g.h.gy=function(){this.Qk();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Qk();this.o&&(a?c?p3(this.o,c,b):p3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):q3(this.o))};
g.h.Lr=function(a,b){this.player.R(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.P().F.unsubscribe("vast_info_card_add",this.pA,this);g.nn(g.lL(this.player),"ytp-iv-drawer-open");for(var a=this.J,b=0,c=a.length;b<c;b++)g.cp(a[b]);this.J.length=0;g.uP.prototype.Y.call(this)};g.JP.annotations_module=B3;g.JP.creatorendscreen=V2;})(_yt_player);
